# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_allow_null_device_beer_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewpidevice',
            name='ota_url',
            field=models.CharField(default=None, help_text='ip/hostname and path used for Over The Air upgrades', max_length=128, null=True),
        ),
    ]
